# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='benefits/', verbose_name='Card')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('barcode', models.CharField(max_length=200, verbose_name='Barcode')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '420x420', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
            ],
            options={
                'verbose_name': 'Benefit',
                'verbose_name_plural': 'Benefits',
            },
        ),
    ]
