# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 12:11
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '1400x900', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
