# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0002_auto_20160310_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='promo_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Promo Code'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '1400x900', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
    ]
