# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-05 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0003_auto_20160516_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='barcode',
            field=models.CharField(blank=True, max_length=200, verbose_name='Barcode'),
        ),
    ]
