# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'UberX/Lyft'), (2, 'UberXL/LyftPlus'), (3, 'Black'), (4, 'SUV'), (5, 'LUX')], verbose_name='Type')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('fuel', models.PositiveSmallIntegerField(choices=[(1, 'E85'), (2, '87 Regular'), (3, '89 Plus'), (4, '91-93 Premium'), (5, 'Diesel'), (6, 'Electric')], verbose_name='Fuel')),
                ('seats', models.PositiveSmallIntegerField(choices=[(4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], verbose_name='Seats')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Car Make',
                'verbose_name_plural': 'Car Makes',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.CarMake', verbose_name='Make')),
            ],
            options={
                'verbose_name': 'Car Model',
                'verbose_name_plural': 'Car Models',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.CarMake', verbose_name='Make'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.CarModel', verbose_name='Model'),
        ),
    ]
