# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20160324_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='cars/', verbose_name='Photo')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Car', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
    ]
