# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 09:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0003_carphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=250, verbose_name='Item')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('condition', models.SmallIntegerField(choices=[(1, 'Good'), (2, 'Medium'), (3, 'Bad')], verbose_name='Condition')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AlterField(
            model_name='carphoto',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='marketplace.Car', verbose_name='Car'),
        ),
    ]
