# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_joboffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalgood',
            name='condition',
            field=models.SmallIntegerField(choices=[(1, 'Brand New (Never Used)'), (2, 'New (Slightly Used)'), (3, 'Used (Good Condition)'), (4, 'Used')], verbose_name='Condition'),
        ),
    ]
