# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 07:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0007_auto_20160328_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joboffer',
            options={'verbose_name': 'Job Offer', 'verbose_name_plural': 'Job Offers'},
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='company',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='driver_requests',
            field=models.ManyToManyField(related_name='offer_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Available'), (2, 'Covered'), (3, 'Completed')], default=1, verbose_name='Status'),
        ),
    ]
