# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_auto_20160330_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='driver_rating',
            field=models.FloatField(default=5.0, verbose_name='Driver Rating'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='owner_rating',
            field=models.FloatField(default=5.0, verbose_name='Owner Rating'),
        ),
    ]
