# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_auto_20160412_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created'], 'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='generalgood',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='joboffer',
            options={'ordering': ['-created'], 'verbose_name': 'Job Offer', 'verbose_name_plural': 'Job Offers'},
        ),
    ]
