# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_joboffer_paid_on_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='title',
            field=models.CharField(default='Job Offer', max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
