# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_auto_20160512_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Car Color',
                'verbose_name_plural': 'Car Colors',
            },
        ),
    ]
