# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_carcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.CarColor', verbose_name='Color'),
        ),
    ]
