# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 07:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='label',
        ),
        migrations.AddField(
            model_name='room',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 19, 7, 38, 28, 89310, tzinfo=utc), verbose_name='Created'),
            preserve_default=False,
        ),
    ]
