# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_relations(apps, schema_editor):
    Room = apps.get_model('chat', 'Room')
    UserRoom = apps.get_model('chat', 'UserRoom')

    for room in Room.objects.all():
        for participant in room.participants.values_list('id', flat=True):
            UserRoom.objects.create(room=room, user_id=participant)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20160419_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unseen', models.PositiveIntegerField(default=0, verbose_name='Number of unseen messages')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='participants2',
            field=models.ManyToManyField(through='chat.UserRoom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(copy_relations, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='room',
            name='participants'
        ),
        migrations.RenameField(
            model_name='room',
            old_name='participants2',
            new_name='participants'
        )
    ]
