# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-18 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20160419_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(null=True, upload_to=b'', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(related_name='participants', through='chat.UserRoom', to=settings.AUTH_USER_MODEL, verbose_name='participants'),
        ),
    ]
