# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 11:44
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='location')),
                ('report_type', models.PositiveSmallIntegerField(choices=[(1, 'Police'), (2, 'TLC'), (3, 'Accident'), (4, 'Traffic Jam'), (5, 'Hazard'), (6, 'Road Closure')], verbose_name='type')),
            ],
        ),
    ]
