# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 12:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 23, 12, 28, 22, 345453, tzinfo=utc), verbose_name='updated'),
            preserve_default=False,
        ),
    ]
