# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 08:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_report_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='declined',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='declined'),
        ),
        migrations.AddField(
            model_name='report',
            name='not_here',
            field=models.BooleanField(default=False, verbose_name='not here'),
        ),
    ]
