# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20160406_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='updated'),
        ),
    ]
