# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160222_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=200, verbose_name='full name'),
            preserve_default=False,
        ),
    ]
