# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 16:18
from __future__ import unicode_literals

import citifleet.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160223_1243'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', citifleet.users.models.UserManager()),
            ],
        ),
    ]
