# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160226_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='_user_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
