# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 11:34
from __future__ import unicode_literals

import citifleet.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20160316_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
            ],
            options={
                'verbose_name': 'Help page',
                'verbose_name_plural': 'Help pages',
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', citifleet.users.models.UserManager()),
                ('with_notifications', citifleet.users.models.AllowNotificationManager()),
            ],
        ),
    ]
