# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_auto_20160329_0700'),
        ('users', '0013_auto_20160318_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='drives',
        ),
        migrations.AddField(
            model_name='user',
            name='car_make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.CarMake'),
        ),
        migrations.AddField(
            model_name='user',
            name='car_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.CarModel'),
        ),
    ]
