# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20160330_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='car_color',
            field=models.PositiveIntegerField(choices=[(1, 'Black'), (2, 'White'), (3, 'Red')], null=True, verbose_name='Car color'),
        ),
        migrations.AddField(
            model_name='user',
            name='car_type',
            field=models.PositiveIntegerField(choices=[(1, 'UberX/Lyft'), (2, 'UberXL/LyftPlus'), (3, 'Black'), (4, 'SUV'), (5, 'LUX')], null=True, verbose_name='Car type'),
        ),
        migrations.AddField(
            model_name='user',
            name='car_year',
            field=models.PositiveIntegerField(null=True, verbose_name='Car year'),
        ),
    ]
