# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-05 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20160406_0837'),
        ('users', '0015_auto_20160331_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notified_reports',
            field=models.ManyToManyField(blank=True, related_name='notified_users', to='reports.Report'),
        ),
        migrations.AlterField(
            model_name='user',
            name='car_color',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Black'), (2, 'White'), (3, 'Red')], null=True, verbose_name='Car color'),
        ),
        migrations.AlterField(
            model_name='user',
            name='car_make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.CarMake'),
        ),
        migrations.AlterField(
            model_name='user',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.CarModel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='car_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'UberX/Lyft'), (2, 'UberXL/LyftPlus'), (3, 'Black'), (4, 'SUV'), (5, 'LUX')], null=True, verbose_name='Car type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='car_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Car year'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hack_license',
            field=models.CharField(blank=True, max_length=150, verbose_name='hack license'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='phone'),
        ),
    ]
