# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vault id'),
        ),
    ]
