# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-28 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_update_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_development',
            field=models.BooleanField(default=False, verbose_name='development?'),
        ),
    ]
