# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-15 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20161012_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='google id'),
        ),
    ]
