# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-30 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevice',
            name='device_os',
            field=models.CharField(choices=[('ios', 'ios'), ('ios', 'ios'), ('iOS', 'iOS'), ('android', 'android'), ('android', 'android'), ('Android', 'Android')], default='android', max_length=50, verbose_name='Device OS'),
        ),
    ]
