# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 16:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/', verbose_name='document')),
                ('expiry_date', models.DateField(null=True, verbose_name='expiry date')),
                ('document_type', models.PositiveSmallIntegerField(choices=[(1, 'DMV License'), (2, 'Hack License'), (3, 'Insurance'), (4, 'Diamond Card'), (5, 'Insurance Certificate'), (6, 'Certificate Of Liability'), (7, 'TLC Plate Number'), (8, 'Drug Test')], verbose_name='document type')),
                ('plate_number', models.CharField(blank=True, max_length=100, verbose_name='tlc plate number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set([('user', 'document_type')]),
        ),
    ]
