# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Under Review'), (2, 'Declined'), (3, 'Confirmed')], default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
