# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20160312_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='expiry date'),
        ),
    ]
