# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalaid', '0002_dmvlawyer_tlclawyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='dmvlawyer',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='insurancebroker',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='tlclawyer',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='rating'),
        ),
    ]
