# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.CharField(max_length=255, verbose_name='message')),
                ('created', models.DateField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'Mass notification',
                'verbose_name_plural': 'Mass notifications',
            },
        ),
    ]
