# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_massnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'New Benefit'), (2, 'Document Expired'), (3, 'Document Verified')], verbose_name='type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.CharField(max_length=255, verbose_name='message')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
            },
        ),
    ]
