# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='massnotification',
            name='category',
            field=models.CharField(default='TLC Alert', max_length=50, verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(default='TLC Alert', max_length=50, verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='category',
            field=models.CharField(default='TLC Alert', max_length=50, verbose_name='category'),
            preserve_default=False,
        ),
    ]
