# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20160317_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='massnotification',
            name='ref_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='massnotification',
            name='ref_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='notification',
            name='ref_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='ref_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='ref_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='ref_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New Benefit'), (2, 'Document Expired'), (3, 'Document Verified'), (5, 'Job Offer Created'), (6, 'Car for Sale/Rent Created'), (7, 'Genera Goods created')], verbose_name='type'),
        ),
    ]
